
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'medicoord_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'medicoord_dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

packages-install-path: "/tmp/dbt-packages"

models:
  medicoord_dbt:
    +materialized: table          # default — write results as real tables